### ISSUE TITLE
query about moves.py

### ISSUE THREAD

**Issue by sukanyasasmal** [MobleyLab/blues#107]
On line 215 & 216 of moves.py, the function  OEPerceiveResidues was called twice successively. Is there a particular reason for the current command structure? Just trying to understand the function..  
OEPerceiveResidues(molecule, OEPreserveResInfo_All)
OEPerceiveResidues(molecule)

**Comment by davidlmobley** [comment]
@nathanmlim , any insight? This sounds to me like it is probably a typo.

**Comment by nathanmlim** [comment]
Addressing in PR #128

**Comment by nathanmlim** [comment]
Fixed.
