### ISSUE TITLE
oeommtools installation

### ISSUE THREAD

**Issue by sukanyasasmal** [MobleyLab/blues#108]
I was trying to install oeommtools as instructed in the blues installation using 
conda install -c openeye/label/Orion oeommtools
But, got the error "PackageNotFoundError: Packages missing in current channels: - oeommtools -> packmol ".

I switched to conda install -c openeye/label/Orion oeommtools -c omnia as instructed in Gaetano's github and it worked fine. There isn't any specific issue, but maybe changing the blues installation instructions might help anyone new.

**Comment by davidlmobley** [comment]
Yes. Submit a PR to change? Thanks.

**Comment by nathanmlim** [comment]
Closing. Addressed in PR #128
