### ISSUE TITLE
Water translation & rotation

### ISSUE THREAD

**Issue by bergazin** [MobleyLab/blues#109]
I'm working on integrating the BLUES WaterTranslationRotationMove class and RandomLigandRotationMove class into one

See code here: https://github.com/MobleyLab/blues/blob/waterscript/Water/WaterTranslationRotation.py

**Comment by davidlmobley** [comment]
You might want to say what for, just for the record.

**Comment by bergazin** [comment]
The goal is to make a NCMC move where a random water is translated within a specified radius of the proteins center of mass to another point within that radius, and then is randomly rotated around it’s center of mass
