### ISSUE TITLE
Freezing water

### ISSUE THREAD

**Issue by amrhamedp** [MobleyLab/blues#142]
I have question regarding freezing of the solvent. I am not sure how can you avoid overlapping of water molecule with the moved ligand in MD phase immediately after you remove the freezing in  the ncmc phase. This can lead to Nan in MD in case it happens

**Comment by davidlmobley** [comment]
Can you clarify slightly? Specifically, usually we only freeze waters that are not near where the ligand would end up, since having a ligand overlap with a frozen water would be very bad. Does that answer your question, or are you asking something different?

**Comment by amrhamedp** [comment]
I was speaking about a case in which the binding site is exposed that may allow the unfrozen water molecules (the ones which are inside the binding site) to move outside and overlap with frozen water molecules.  Sorry I mentioned the ligand incorrectly.

**Comment by davidlmobley** [comment]
So, the unfrozen and frozen waters are all still physically present and fully interacting, so it's impossible that they would leave and overlap with frozen waters (the sterics would prevent that, or more specifically, they would result in moves that caused this to happen being rejected). Does that answer your question? 

The final result of a move proposal (which is evaluated for acceptance or rejection) is a fully interacting system with the ligand and possibly its environment moved around. The move is accepted or rejected based on the work done in the process of (perturbation & propagation, aka relaxation) so if the final PHYSICAL configuration (with full interactions) is quite unfavorable (as it would be if there are clashes between water molecules) it will get rejected.

**Comment by amrhamedp** [comment]
Yes that absolutely answers my question. Thank you  very much for that clear answer.
