### ISSUE TITLE
Acceptance Ratio: 0.0 

### ISSUE THREAD

**Issue by kexul** [MobleyLab/blues#174]
Hi, I'm testing BLUES with the `1H1R` [ligand](https://www.rcsb.org/structure/1H1R), which was [shown](https://pubs.acs.org/doi/10.1021/ct300911a) to have two possible binding modes: 
![企业微信截图_16572040286773](https://user-images.githubusercontent.com/5920217/177798065-98b1e224-f318-4400-92e6-4e7cd43027c5.png)

I'm using the default [protocol ](https://github.com/MobleyLab/blues/blob/master/examples/rotmove_cuda.yml) provided in the example.  The BLUES simulation has run for 100 iteration, but the acceptance ratio is 0.0. Is there something I can do? Thanks!

Here are the input and output files: 
[temp.zip](https://github.com/MobleyLab/blues/files/9064652/temp.zip)

**Comment by kexul** [comment]
I've tried setting ` nprop: 3  nstepsNC: 17000`, the acceptance ratio is still 0.0.

**Comment by davidlmobley** [comment]
I hadn't gotten a moment to answer this, but you just closed it... did you resolve this issue somehow?

**Comment by kexul** [comment]
Hi @davidlmobley , thanks for your attention! 

After reading your paper more carefully, I realized that the default `RandomLightRotationMove` might struggle to rotate the ligand, considering the shape of the binding site, so the acceptance ratio is zero: 
![企业微信截图_16573354603538](https://user-images.githubusercontent.com/5920217/178089091-8f47d58d-9c1a-423e-a97f-ca94c1593408.png)

In this case, to validate the possible binding pose due to rotation of the toluene group, maybe a custom `Torsional move` would be more appropriate. What do you think? 

I'd like to try the implementation here: https://github.com/MobleyLab/blues/pull/164.

**Comment by davidlmobley** [comment]
Right, yes, we've found that for larger ligands (and those with rotatable bonds) the odds of finding a new reasonable pose just by rotating the whole ligand get really really low. So we often run into the issue you described. If you're just interested in where the aromatic ring points, then you want a torsional move; I very much agree.

Will try to look at your PR soon, though I probably can't do much of a code review -- the students working on BLUES have graduated and I don't have someone currently developing it; I'd like to do so again, but that requires finding the right person first. 

Can I ask where you're based/in what group? Feel free to e-mail if you'd prefer.
