### ISSUE TITLE
Enforce symmetry during NCMC move

### ISSUE THREAD

**Issue by sgill2** [MobleyLab/blues#19]
In order to keep detailed balance (easily) during an NCMC move it's necessary to keep the propagation/perturbation steps during an NCMC move symmetric. We should probably enforce this symmetry as best as we can when users are using this code themselves, so they don't unwittingly alter the acceptance criteria. This probably involves at least these three things:
1. Include a default lambda switching protocol that is symmetric.
2. Include documentation warning about changing the lambda switching protocol and the importance of the symmetry
3. Include additional perturbation moves (like the rotational/smart darting moves) at a symmetric point in the NCMC move (And possibly a way to enforce it?). 
I'll see about addressing these points in the coming days.

**Comment by davidlmobley** [comment]
@sgill2 - did you need help figuring out how to enforce this?

**Comment by davidlmobley** [comment]
I think this is closed based on Nathan's refactoring -- we're baking symmetry into the move engines themselves so the users won't be modifying it. Would you agree, @sgill2 ?

**Comment by sgill2** [comment]
The user could still change at what point the move takes place with some finagling, but it defaults to the halfway point. I think it'd be fine if we closed this for now. If it seems like there's a particular need for non-symmetric moves we could revisit this.

**Comment by sgill2** [comment]
Just for my own reference if we do revisit this we should use either the Lepton parser for openmm, or openmmtools.utils which contains (I believe) a Lepton parser as well, except perhaps more python friendly.
