### ISSUE TITLE
Exception: Particles not set for NC context

### ISSUE THREAD

**Issue by nathanmlim** [MobleyLab/blues#25]
Offending [line](https://github.com/MobleyLab/blues/blob/master/blues/ncmc.py#L416) causes the exception below:

>   File "example.py", line 105, in runNCMC
>     alchemical_correction=True)
>   File "/mnt/SG1TB/Github/testenv/blues/blues/ncmc.py", line 417, in runSim
>     nc_stateinfo = nc_context.getState(True, False, False, False, False, periodic)
>   File "/home/limn1/anaconda3/envs/blues_test/lib/python3.5/site-packages/simtk/openmm/openmm.py", line 3969, in getState
>     self._getStateAsLists(getP, getV, getF, getE, getPa, getPd, enforcePeriodic, groups_mask)
>   File "/home/limn1/anaconda3/envs/blues_test/lib/python3.5/site-packages/simtk/openmm/openmm.py", line 3919, in _getStateAsLists
>     return _openmm.Context__getStateAsLists(self, getPositions, getVelocities, getForces, getEnergy, getParameters, getParameterDerivatives, enforcePeriodic, groups)
> Exception: Particle positions have not been set

Line 416 is meant to create an empty positions array for the nc context, but the new versions of OpenMM cause the exception above to be raised. 

Possible solution would be to just initialize an empty numpy array using the length of atoms from the md context?

**Comment by sgill2** [comment]
Should be fixed by #27.
