### ISSUE TITLE
SimNCMC.rotationalmove() rotates the positions at the start of the ncmc step

### ISSUE THREAD

**Issue by sgill2** [MobleyLab/blues#26]
SimNCMC.rotationalmove() rotates the ligand positions from the start of the ncmc step, when it should use the positions from wherever the ligand is at currently after the pertubation/propogation steps.

**Comment by davidlmobley** [comment]
That sounds serious. 

Another reason we need more tests. It would be good to think about how we can test teh basic validity of a perturbation/propagation cycle.

**Comment by davidlmobley** [comment]
This was resolved by #27, right? Closing...
