### ISSUE TITLE
Correct alchemical correction equation

### ISSUE THREAD

**Issue by sgill2** [MobleyLab/blues#40]
The alchemical correction factor originally used the formula:
correction_factor = -1.0*((norm_newPE - alc_newPE) - (oldPE - alc_oldPE))*(1/nc_integrator.kT),
where 
norm_newPE is the potential energy at the end of the NCMC iteration using softcore interactions, 
alc_oldPE is the potential energy at the start of the NCMC iteration using softcore interactions,
and norm_newPE and oldPE refer to the potential energies at the end of the NCMC iteration respectively using the normal steric/electrostatic interactions. (the kT portion is to cast the potential energy in terms of kT).

The actual correction factor should be:
correction_factor = (alc_oldPE - oldPE + norm_newPE - alc_newPE)*(1/nc_integrator.kT)
With the semi-cycle worked out in the attached picture.
 ![img_5043](https://cloud.githubusercontent.com/assets/11822321/24420128/924e0158-13a6-11e7-8a51-74ed85f5be59.JPG)

**Comment by davidlmobley** [comment]
Resolved by #41 .
