### ISSUE TITLE
Do new point release

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/blues#49]
We should do a new point release now that #44 is merged. 0.0.3? @nathanmlim , want to do this? You would use the "releases" tab and model it after the other ones. This SHOULD automatically trigger a new DOI via zenodo as well.

**Comment by nathanmlim** [comment]
@davidlmobley I think we can cut a release and update the packages after the PR #52 is merged? So at least there is some documentation explaining the new framework with the release.

**Comment by davidlmobley** [comment]
Closed.
