### ISSUE TITLE
Allowing flexibility in integrator choice

### ISSUE THREAD

**Issue by sgill2** [MobleyLab/blues#51]
Currently the SimulationFactory.generateSimFromStruct() method doesn't allow for specification of integrators and an NCMCVVAlchemicalIntegrator is automatically used as the integrator. I think allowing an option to either specify and/or pass in an integrator would be beneficial.

**Comment by sgill2** [comment]
Any particular thoughts on this @nathanmlim?

**Comment by davidlmobley** [comment]
@sgill2 - my perspective is that we should figure out what integrator(s) we should use in which situations internally and make this choice in a way which is generally hidden from the user. 

That is to say, I don't think we want this to be an option, though I could be backed off from that position to the position that it should be an experts-only or hidden option to make your life easier.

**Comment by sgill2** [comment]
The easiest way to test which integrators work best internally would be to have way to specify it somewhere in the run script, but I agree that it should be a mostly hidden option.

**Comment by davidlmobley** [comment]
Let's wait for Nathan to weigh in. On one hand we don't want things to be unnecessarily difficult for you, but on the other we do want to set things up in a way where a user doesn't have to know much to get what we believe are best practices.

**Comment by davidlmobley** [comment]
@nathanmlim - thoughts? (I believe you're about to start cross-comparing integrators in some tests so this becomes more relevant to you.)

**Comment by sgill2** [comment]
From the set of tests I ran, it seems like the openmmtools set of splitting integrators performs better than the old VV based, so we've reverted to using that as our default for now.
