### ISSUE TITLE
Finish testing integrators and swap default integrator

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/blues#61]
In #50 and (to a lesser extent #53 ) we've been discussing changing the default integrator to `NonequilibriumLangevinIntegrator`. We need to do so, but first we need to finish testing:

@sgill2 has some questions he needs to answer (and re-test if needed) which are asked here: https://github.com/MobleyLab/blues/issues/50#issuecomment-297180826 (and could be answered on this issue) for tests on lysozyme, I believe.

@nathanmlim is going to test on a soluble epoxide hydrolase (?) system, cross-comparing this with the current integrator and report back.

Once we've tested a bit more carefully and documented the results it sounds like we should be able to switch, which will resolve issues with code duplication discussed in #50 and will hopefully also improve acceptance, etc.

**Comment by sgill2** [comment]
Closed via #89. Testing showed that the new `AlchemicalExternalLangevinIntegrator` performed better than the old VV integrator.
