### ISSUE TITLE
Constraint handling in SimulationFactory.generateSystem()

### ISSUE THREAD

**Issue by sgill2** [MobleyLab/blues#68]
I'm still trying to figure out the integrator differences in acceptance but in the process I noticed that the constraints may not be handled appropriately in the generateSystem() method.https://github.com/MobleyLab/blues/blob/master/blues/ncmc.py#L234-L247

Specifically while generateSystem() takes a `constraint` argument, that argument is never actually used in the function itself, thus the constraints for systems generated this way will always be `None`.

**Comment by sgill2** [comment]
Could you double check me on this when you have a moment @nathanmlim?

**Comment by nathanmlim** [comment]
Closing. Solved by PR #69
