### ISSUE TITLE
Option to output NCMC simulation frames

### ISSUE THREAD

**Issue by sgill2** [MobleyLab/blues#71]
To debug at the ncmc level it'd be helpful to have the ability to output frames from the ncmc simulation. Currently the only way to do this is to use the simulation.writeFrame() method, which isn't ideal for two reasons:
1. You'd have to go and modify the blues code directly
2. Using ParmEd (which is what simulation.writeFrame uses) to write out the files is very slow

To address this I'm thinking of adding–to the simulation opt dict–an option to specify if ncmc simulation frames are wanted and at what interval to output those frames using openmm reporters.

**Comment by nathanmlim** [comment]
I agree that we could add more functionality for debugging.

On regards to speed with parmed.Structure.save() or what `simulation.writeFrame()` calls are you trying to write out to a PDB? Generally, writing to a PDB is slower than other formats and that functionality isn't intended to be used to write out a trajectory. Perhaps it wasn't a good idea to put that function call into the ncmc stage...so I'm on board for having a class that we can use to define our reporters to handle writing out trajectories.

Right now, I have just the simulation status reporter embedded into the [generateSimFromStruct](https://github.com/MobleyLab/blues/blob/master/blues/ncmc.py#L318) function, so we would have to move that out into it's own class/function.
