### ISSUE TITLE
Plan MoveMIxtureEngine

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/blues#75]
Ultimately, we will want to combine various types of moves, either separately with different probablities, or sometimes in combination (smart darting plus random rotation). Perhaps the separate application might look like this:

```python
mover = MoveMixtureEngine( [ ligmove, [sidechainmove_val111, sidechainmove_leu113], loopmove ], nstepsNC, probabilities = 0.5, 0.25, 0.25] )
Simulation(mover, everything_else***)
Simulation.run()
```
`Simulation` should be able to take either a "plain" move, e.g. `Simulation(ligmove)` or a `MoveMixtureEngine` object.

But how would we alter this if we want to apply moves simultaneously?

**Comment by sgill2** [comment]
My initial thoughts to handle combination moves would be to make another `Move` object that takes in a list of `Move` objects as input. Then it's `move()` method when called would loop over the `Move` objects in the list and call their `move()` method.

basic implementation
```python
def Class ComboMove(Move)
    def __init__(move_list):
        self.move_list = move_list
    def move(...)
        for single_move in self.move_list:
            single_move.move(...)
```
pseudocode use case
```python
movelist = [sidechain_move, ligmove]
ComboMove = CombinationMove(move_list)

mover = MoveMixtureEngine(ComboMove)
Simulation(mover, everything_else***)
Simulation.run()

```

**Comment by davidlmobley** [comment]
@sgill2 - this sounds interesting. Can you be slightly more explicit -- in what you're proposing, the `ComboMove` class would accommodate moves which are going to be applied sequentially in the order they are input; is that correct?

This actually sounds like a rather general strategy.

But -- one thing we maybe need to think about is reversibility. Specifically, are there certain types of combo moves (or all combo moves?) which would need to be applied in both orders in order to ensure reversibility?

**Comment by sgill2** [comment]
>Can you be slightly more explicit -- in what you're proposing, the ComboMove class would accommodate moves which are going to be applied sequentially in the order they are input; is that correct?

Yes, it would perform the moves in the order they are in the list.

>But -- one thing we maybe need to think about is reversibility. Specifically, are there certain types of combo moves (or all combo moves?) which would need to be applied in both orders in order to ensure reversibility?

This is one of my concerns as well. Right now the types of moves we have implemented are communicative; the order they are performed in doesn't matter, but other moves possibly could. Like you were implying, I'd lean to imposing a reversibility in the order of the performed moves. So we could make the `ComboMove` innately perform the reverse sequence half the time (and document it so it's clear what `ComboMove` is actually doing).
So a revised `ComboMove` could look kinda like: 
```
def Class ComboMove(Move)
    def __init__(move_list):
        self.move_list = move_list
    def move(...)
        rand = np.random.random()
       if rand > 0.5:
            for single_move in self.move_list:
                 single_move.move(...)
       else:
            for single_move in reverse(self.move_list):
                 single_move.move(...)
```
That shouldn't affect any communicative move combinations, but should handle the reversibility of the non-communicative cases, I think.

**Comment by davidlmobley** [comment]
@sgill2 - that sounds great. I THINK the word you're after is "commutative" not "communicative" but this would be a good way to ensure no one breaks things by inventing non-commutative moves.

**Comment by sgill2** [comment]
Opps, yeah haha. Sometimes it's tough being communicative about commutative properties :S
