### ISSUE TITLE
Character encoding issues in README.md

### ISSUE THREAD

**Issue by khburley** [MobleyLab/blues#90]
<img width="1141" alt="screen shot 2017-07-31 at 4 24 35 pm" src="https://user-images.githubusercontent.com/15110940/28835492-55dabc28-769a-11e7-9b06-f2859fd1fce6.png">

There is an issue in the README.md file related to character encoding that results in this error during installation of blues.  It can be bypassed by deleting the entire contents of the README.md file.

**Comment by davidlmobley** [comment]
@sgill2 - can you have a quick look? I think there is some sort of bad character somewhere in the README.md. It's possible we won't be able to see it in the plain text (maybe) but Kalli's test suggests a simple way to track it down (delete parts of the file until we isolate where it is).

**Comment by sgill2** [comment]
Yeah, I'll look into it.

**Comment by sgill2** [comment]
@khburley When I cloned a fresh master branch and ran `python setup.py install` it ran without errors for me. Could you try cloning the master branch again and tell me if you still see the same issue?

**Comment by khburley** [comment]
<img width="917" alt="screen shot 2017-08-01 at 11 37 25 am" src="https://user-images.githubusercontent.com/15110940/28841115-fe9cbb0a-76ad-11e7-8c7b-c5664c999e68.png">

@sgill2 Hmm... So I just tried it again and it works fine if I install it locally, but I still get that error specifically when I try to install on greenplanet.

**Comment by sgill2** [comment]
@khburley Weird. I just tried it on greenplanet, but it worked fine for me there too. But I was using python2.7 there; I'll update you when I try with python3.

**Comment by sgill2** [comment]
@khburley I've tested with python 2.7 and 3.5 and they both work for me.  I'm tending towards thinking this isn't a repo specific bug. Maybe the `README.md` file got corrupted somehow? At the very least you have a workaround if you need it (deleting the `README.md` lines).

Let me know if you continue having problems with this.

**Comment by sgill2** [comment]
While I was closing old issues I saw that this is pretty much identical to #65. Do you remember if you did anything to address this @nathanmlim, or did it just go away on it's own?

**Comment by nathanmlim** [comment]
It seemed to go away on it’s own. I don’t quite recall doing anything in particular to solve this issue other than a full clean install.

**Comment by sgill2** [comment]
Alright, I'm going to close this issue for now. If this crops up again we can revisit this.
